item {
 id: 1
 name: 'black'
}
item {
 id: 2
 name: 'blue'
}
item {
 id: 3
 name: 'brown'
}
item {
 id: 4
 name: 'green'
}
item {
 id: 5
 name: 'pink'
}
item {
 id: 6
 name: 'red'
}
item {
 id: 7
 name: 'white'
}
item {
 id: 8
 name: 'yellow'
}
